[platformio]
src_dir = esp32_lcd_keypad_i2c

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  marcoschwartz/LiquidCrystal_I2C@1.1.4
  chris--a/Keypad@3.1.1
build_src_filter =
  +<*>
