; PlatformIO project for board 1: ESP32 + 3x4 keypad + LCD 16x2 I2C
[platformio]
src_dir = .
include_dir = .

[env:esp32-keypad]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  chris--a/Keypad@3.1.1
  marcoschwartz/LiquidCrystal_I2C@1.1.4
build_flags =
  -DCORE_DEBUG_LEVEL=0
